### PR TITLE
Publishing sassdoc docs

### PR DESCRIPTION
**Pull request by KittyGiraudel**
I have done some tiny changes for the upcoming SassDoc docs.

To finalize the whole thing, you need to:
1. Merge this PR.
2. Install SassDoc on your machine: `npm install -g sassdoc@2.0.0-rc.16`.
3. Install sassdocify on your machine: `npm install -g sassdocify`.
4. Make sure it is in your path: `export PATH="$PWD/bin:$PATH"`.
5. Run sassdocify: `sassdocify`.
6. Publish on GHPages: `cd .pages && git push -u origin gh-pages`.

Then, every time you want to refresh the docs, you only have to repeat steps 5 and 6, or in a single command: `sassdocify && cd .pages && git push -u origin gh-pages`.

Everything else is automated. :)

### CODE REVIEW

**Comment by lunelson** [comment]
Hmm. I get the following:

``` sh
> sassdocify
readlink: illegal option -- f
usage: readlink [-n] [file ...]
find: ftsopen: No such file or directory
No documentable file found in source directory.
```

**Comment by KittyGiraudel** [comment]
Ping @valeriangalliat.

**Comment by KittyGiraudel** [comment]
What OS do you use @lunelson?

**Comment by valeriangalliat** [comment]
Might be an incompatibility with Apple's `readlink` (though I believed it has the `-f` option since FreeBSD have it too).

I fixed this in sassdocify 0.3.1, @lunelson please update and try aigain.

**Comment by lunelson** [comment]
Thanks @valeriangalliat that seemed to work better; but the git checkout command seemed to hang up:

``` sh
> sassdocify
➜ rm -rf .pages
➜ git clone . .pages
Cloning into '.pages'...
done.
➜ git -C .pages checkout --orphan gh-pages
Unknown option: -C
usage: git [--version] [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]
           [-p|--paginate|--no-pager] [--no-replace-objects] [--bare]
           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]
           [-c name=value] [--help]
           <command> [<args>]
```

**Comment by lunelson** [comment]
@HugoGiraudel my OS is mavericks 10.9.5

**Comment by valeriangalliat** [comment]
Hmm the `-C` Git option is since Git 1.8.5.

Published 0.3.2 with compatibility fix, thanks @lunelson for testing sassdocify and helping make it more compatible. :)

You can try one more time (last one I hope)!

**Comment by lunelson** [comment]
Almost there I think :). This time I got an error to do with sass-convert:

``` sh
> sassdocify
➜ rm -rf .pages
➜ git clone . .pages
Cloning into '.pages'...
done.
➜ gitc .pages checkout --orphan gh-pages
Switched to a new branch 'gh-pages'
➜ gitc .pages remote set-url origin https://github.com/lunelson/sass-maps-plus.git
➜ gitc .pages rm -rf --ignore-unmatch .
rm '.gitignore'
rm '.sassdocrc'
rm 'LICENSE'
rm 'README.md'
rm 'TODO.todo'
rm '_beta.scss'
rm '_sass-maps-plus.scss'
rm 'bower.json'
rm 'gulpfile.js'
rm 'lib/sass-list-maps.rb'
rm 'package.json'
rm 'sache.json'
rm 'sass-hash-plus.jpg'
rm 'sass-hash-plus.psd'
rm 'sass-hash.jpg'
rm 'sass-maps-plus.gemspec'
rm 'sass-maps-plus.todo'
rm 'test/_list-maps-advanced.scss'
rm 'test/_list-maps-basic.scss'
rm 'test/_maps-advanced.scss'
rm 'test/_maps-basic.scss'
rm 'test/test.css'
rm 'test/test.scss'
➜ sassdoc /Users/lunelson/Git/Projects/LN/sass-maps-plus --dest .sassdoc
[2015-01-14 08:33:27] [ERROR] Invalid "sass-convert" version, must be >=3.4.5
```

**Comment by valeriangalliat** [comment]
Well this time I think you have to upgrade Sass (that provides `sass-convert`)… I'm not sure it's easy (or even possible) to make SassDoc compatible with `sass-convert < 3.4.5` (I believe that's why the version check is there).

However I don't see `.sass` files in the folder you're documenting so I don't get why `sass-convert` is even invoked in the first place. @pascalduez?

**Comment by KittyGiraudel** [comment]
> However I don't see .sass files in the folder you're documenting so I don't get why sass-convert is even invoked in the first place. @pascalduez?

Because it is now implied with SassDoc version 2. 

Is there a way you could `gem update sass` @lunelson?

**Comment by lunelson** [comment]
One step closer ! Something erroring out still. Is it possible it's picking up the wrong file? I also have a file called `_beta.scss` in there, it's just a junk file. Maybe I have to hide this from `sassdocify` somehow?

``` sh
> sassdocify
➜ rm -rf .pages
➜ git clone . .pages
Cloning into '.pages'...
done.
➜ gitc .pages checkout --orphan gh-pages
Switched to a new branch 'gh-pages'
➜ gitc .pages remote set-url origin https://github.com/lunelson/sass-maps-plus.git
➜ gitc .pages rm -rf --ignore-unmatch .
rm '.gitignore'
rm '.sassdocrc'
rm 'LICENSE'
rm 'README.md'
rm 'TODO.todo'
rm '_beta.scss'
rm '_sass-maps-plus.scss'
rm 'bower.json'
rm 'gulpfile.js'
rm 'lib/sass-list-maps.rb'
rm 'package.json'
rm 'sache.json'
rm 'sass-hash-plus.jpg'
rm 'sass-hash-plus.psd'
rm 'sass-hash.jpg'
rm 'sass-maps-plus.gemspec'
rm 'sass-maps-plus.todo'
rm 'test/_list-maps-advanced.scss'
rm 'test/_list-maps-basic.scss'
rm 'test/_maps-advanced.scss'
rm 'test/_maps-basic.scss'
rm 'test/test.css'
rm 'test/test.scss'
➜ sassdoc /Users/lunelson/Git/Projects/LN/sass-maps-plus --dest .sassdoc
[2015-01-14 10:59:07] [ERROR] [object Object]
```

**Comment by KittyGiraudel** [comment]
Haha, well this is definitely a very useful error...

> [2015-01-14 10:59:07] [ERROR] [object Object]

**Comment by KittyGiraudel** [comment]
I don't think `_beta.scss` is the issue. The function is undocumented so SassDoc just ignores it altogether.

**Comment by KittyGiraudel** [comment]
Ping @pascalduez. Ping @fweinb.

**Comment by lunelson** [comment]
Yeah I love those kinds of errors

**Comment by KittyGiraudel** [comment]
Desperate situations call for drastic remedies. Could you please give us the output of:

```
SASSDOC='sassdoc --verbose' sassdocify
```

**Comment by pascalduez** [comment]
If there is no `.sass` files `sass-convert` should just pass trough. I'm gonna check this.

The reason `sass-convert` needs Sass >=3.4.5 is it includes fixes that preserve comments.

**Comment by pascalduez** [comment]
I can't reproduce the `sass-convert` thing.

If there is no `.sass` files, the sass-convert binary checks are not invoked.
Tested on `sass-maps-plus` as well as own tests.

@lunelson are you running the command on a clean repo ? I tested on a clone of the `master` branch.

**Comment by lunelson** [comment]
Hi guys, okay I was away but now I'm back, on a different machine and clean repo up to date with this one. I tried @HugoGiraudel 's command above and got this:

``` sh
> SASSDOC='sassdoc --verbose' sassdocify
➜ rm -rf .pages
➜ git clone . .pages
Cloning into '.pages'...
done.
➜ gitc .pages checkout --orphan gh-pages
Switched to a new branch 'gh-pages'
➜ gitc .pages remote set-url origin git@github.com:lunelson/sass-maps-plus.git
➜ gitc .pages rm -rf --ignore-unmatch .
rm '.gitignore'
rm '.sassdocrc'
rm 'LICENSE'
rm 'README.md'
rm 'TODO.todo'
rm '_beta.scss'
rm '_sass-maps-plus.scss'
rm 'bower.json'
rm 'gulpfile.js'
rm 'lib/sass-list-maps.rb'
rm 'package.json'
rm 'sache.json'
rm 'sass-hash-plus.jpg'
rm 'sass-hash-plus.psd'
rm 'sass-hash.jpg'
rm 'sass-maps-plus.gemspec'
rm 'sass-maps-plus.todo'
rm 'test/_list-maps-advanced.scss'
rm 'test/_list-maps-basic.scss'
rm 'test/_maps-advanced.scss'
rm 'test/_maps-basic.scss'
rm 'test/test.css'
rm 'test/test.scss'
➜ sassdoc --verbose /Users/lunelson/Git/Projects/Sass/sass-maps-plus --dest .sassdoc
--dest is not recognized
```

Looking at the files in the directory after this, a `.pages` directory and a `.sassdocrc` file have been created.

**Comment by KittyGiraudel** [comment]
> Looking at the files in the directory after this, a .pages directory

Intended. Then you'll be able to go `cd .pages && git push -u origin gh-pages` to publish your docs.

> a .sassdocrc file have been created.

This comes from this very PR. It is the configuration file for SassDoc.

Could you please tell me which version of SassDoc you use? I think I've found the issue.

``` scss
sassdoc --version
```

**Comment by lunelson** [comment]
It reports `2.0.0-rc.6`

**Comment by KittyGiraudel** [comment]
Okay, that is what I suspected. Please, run `npm install sassdoc@2.0.0-rc.16`, then retry.

**Comment by valeriangalliat** [comment]
And if you use npm 1.0 it will refuse to install the latest RC, and you might have to run `npm install npm` before to upgrade to 2.0.

**Comment by KittyGiraudel** [comment]
> npm install npm 

This one never fails to baffle me.

**Comment by lunelson** [comment]
That did it! I never knew about upgrading npm that way, quite funny. Docs are online: 

[http://lunelson.de/sass-maps-plus/](http://lunelson.de/sass-maps-plus/). 

Thanks to all of you for your help!

**Comment by KittyGiraudel** [comment]
OH YEAH

**Comment by valeriangalliat** [comment]
@lunelson Awesome!

Also I see you're still using the 1.0-style default values `(default)` while we now use square brackets for this `[default]`.

You can run this [script](https://github.com/SassDoc/sassdoc/issues/303#issuecomment-68525038) to migrate your comments, though it's a dumb script and will fail on default values containing parentheses (like `(length($list))` which will be converted to `[length[$list]]`) so you'll have to fix some stuff manually anyway.

**Comment by pascalduez** [comment]
`npm install npm@latest -g`
`npm install sassdoc@beta -g` 

To be safe and up to date.

**Comment by lunelson** [comment]
Thanks for those tips!

**Pull request merged**
